### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by tkayalvizhi** [stALabsLLC/Kayal#1]
#[]([](https://github.com/stALabsLLC/Kayal/blob/a8091cb2fc10967b06eae30690c50fe00b645372/pom.xml#L29))

**My getWardData function [src/main/java/com/mycompany/app/App.java](url) fails to execute. It is supposed to fetch data from dynamodb table based on the query parameter: id. But I'm stuck with not being able to run the function because of this NoClassDeffoundError. I'm not sure why**

Error Message: 

START RequestId: 9b148320-ecbd-426d-8cb0-c12447173574 Version: $LATEST
Error loading class com.mycompany.app.App: com/amazonaws/services/simplesystemsmanagement/AWSSimpleSystemsManagementClientBuilder: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/amazonaws/services/simplesystemsmanagement/AWSSimpleSystemsManagementClientBuilder
	at com.mycompany.app.App.<clinit>(App.java:28)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagementClientBuilder. **### Current classpath: file:/var/task/**

END RequestId: 9b148320-ecbd-426d-8cb0-c12447173574
REPORT RequestId: 9b148320-ecbd-426d-8cb0-c12447173574	Duration: 342.78 ms	Billed Duration: 343 ms	Memory Size: 512 MB	Max Memory Used: 88 MB	Init Duration: 216.97 ms	
Unknown application error occurred
java.lang.NoClassDefFoundError

**Comment by tkayalvizhi** [comment]
I was using a  Java version 15 in maven but Lambda uses Java Cornetto 11 / Java 8.  Corrected that and it worked fine.
